### ISSUE TITLE
Implement custom health factor slider

### ISSUE THREAD

**Issue by SolcAndMe** [fiatdao/fiat-ui-i#10]
Remove antd dependency

**Comment by 0xTARC** [comment]
id like to suggest this as the new base

https://www.radix-ui.com/docs/primitives/components/slider

no need to import all of antd just for a slider, plus DX of antd is gross as hell
radix is super minimal and accessible

**Comment by Rudi114** [comment]
The component TARC mentioned above is probably more 'plug and play' but if we need something that allows for more custom css, [React Slider](https://www.npmjs.com/package/react-slider) is really powerful

[Gov App Code Example](https://github.com/fiatdao/gov-ui-i/tree/main/apps/council-frontend/src/ui/base/Slider)

**Comment by 0xTARC** [comment]
> The component TARC mentioned above is probably more 'plug and play' but if we need something that allows for more custom css, [React Slider](https://www.npmjs.com/package/react-slider) is really powerful
> 
> [Gov App Code Example](https://github.com/fiatdao/gov-ui-i/tree/main/apps/council-frontend/src/ui/base/Slider)

going with react-slider, radix slider doesn't implement marks
