### ISSUE TITLE
Fix withdrawable collateral calc

### ISSUE THREAD

**Issue by nbundi** [fiatdao/fiat-ui-i#118]
In the leverStore the `withdrawableCollateral` is computed the wrong way: https://github.com/fiatdao/fiat-ui-i/blob/611a35ab6169d0a18d105d3f0158180b320d4e37/src/state/stores/leverStore.ts#L489

Currently we 
1. fetch the `fiatForUnderlier` amount, the amount of underlier tokens required to buy FIAT debt, from the leverAction
2. compute the `fiatForUnderlierRate = fiatForUnderlier/debt`
3. compute `withdrawableCollateral = collateral - (debt+dueAtMaturity) / fiatForUnderlierRate`

thereby we apply the `fiatForUnderlierRate` the wrong way (should be mul not div).

you can see this the following way:

- `withdrawableCollateral` should be `collateral` minus the underliers required to pay back the position's debt. 
- we could compute this underlier required to pay back debt (without interest) by: `underliersToPayBackDebt = userActions.fiatForUnderlier(fiat, debt, collateralType)`
- then we perform an intermediate step of calculating `fiatForUnderlierRate = underliersToPayBackDebt / debt`
so in order to compute the withdrawable collateral we have to
`withdrawableCollateral = collateral - (debt+dueAtMaturity) * fiatForUnderlierRate`

we can also skip the intermediate step (bc `fiatForUnderlierRate` is not used anywhere else) and simply compute
`withdrawableCollateral = collateral - userActions.fiatForUnderlier(fiat, debt + dueAtMaturity, collateralType)`

**Comment by SolcAndMe** [comment]
@nbundi I think this is now fixed on main
