### ISSUE TITLE
Add 'max' clickable text to the label of all numeric Inputs

### ISSUE THREAD

**Issue by SolcAndMe** [fiatdao/fiat-ui-i#12]
e.g. for Create Position: 

Underlier to swap (**max**)

**Comment by 0xTARC** [comment]
Can re-use InputLabel component (currently only used in CreatePositionModal. need to implement in ModifyPositionModal)
 https://github.com/fiatdao/fiat-ui-i/blob/ac600d7edea4f11f0be22f2f02b4879ffcd90504/src/components/InputLabel.tsx

**Comment by 0xTARC** [comment]
addressed in
b6cce4822e135b389718f98c82f11a861be62d5b
