### ISSUE TITLE
Convert the dryrun calls with sendAndWait calls

### ISSUE THREAD

**Issue by 0xTARC** [fiatdao/fiat-ui-i#5]
- [x] Loading signifiers where appropriate.
- [ ] Error states for form inputs that disable sending txns.
1. FIAT minted would be below the debt floor 
2. slippage / price impact to high
3. all other errors which we can catch via the dryrun method - which already decodes the error message

1., 2. should be checked sync, 3. on the other would be done implicitly. but all the messages should be in the red framed box somewhere in the form.

we have to present an error message somewhere, in a red frame with red font.

kinda like this
<img width="885" alt="image" src="https://user-images.githubusercontent.com/97852365/199761076-f7adf0c7-97e7-4cf8-bd9c-ef718e362bea.png">

- [ ] When transaction is sent, add the transaction to the rainbow kit [recent transactions](https://www.rainbowkit.com/docs/recent-transactions)

**Comment by 0xTARC** [comment]
doing the forms rn and then i'll do this one

**Comment by SolcAndMe** [comment]
basic errors to catch are:
1. FIAT minted would be below the debt floor 
2. slippage / price impact to high
3. all other errors which we can catch via the dryrun method - which already decodes the error message

**Comment by SolcAndMe** [comment]
errors need to be handled with this: https://github.com/fiatdao/lever-ui/issues/4#issue-1434832296
