### ISSUE TITLE
Replace Input Component

### ISSUE THREAD

**Issue by 0xTARC** [fiatdao/fiat-ui-i#72]
* Add validation to Input component (only non-negative decimal values)
* Make it a controlled component, with sane but flexible defaults for styling
* Replace Next UI input, because it can't satisfy the above two

**Comment by SolcAndMe** [comment]
blocked by #7

**Comment by 0xTARC** [comment]
started experimenting here: numeric-input-experiment
we should rip out next ui Input component, it has a horrendous api. it's uncontrolled by default. to make it controlled you need to pass `value` an array of strings. wtf?
