### ISSUE TITLE
Visual clean up

### ISSUE THREAD

**Issue by SolcAndMe** [fiatdao/fiat-ui-i#8]
- [x] Add svg icons and links for protocol and tokens for Collateral Types and Positions table
- [x] Add TVL metrics to Collateral Types table
- [x] Remove tokenId from Positions table
- [x] Add maturity column to Positions table
- [x] Show USD values below collateral amounts
- [x] Add FIAT balance to rainbowkit status bar
- [x] Add 'experimental' disclaimer to top bar
- [x] Show mainnet disclaimer when user is not connected (since rainbow doesn't show it in that state)

**Comment by jFarms** [comment]
For tvl first express as native token, but eventually add usd value

**Comment by jFarms** [comment]
Rainbow wallet, show fiat balance instead of eth balance

**Comment by jFarms** [comment]
Verify correct chain is connected

**Comment by SolcAndMe** [comment]
https://github.com/fiatdao/lever-ui/issues/11

**Comment by SolcAndMe** [comment]
> Verify correct chain is connected

We don't want to verify that the correct chain is connected. We want to show the Network name if the user is not connected because it defaults on mainnet state.

**Comment by jFarms** [comment]
Should we show $ amount under Normal Debt in positions table?

**Comment by 0xTARC** [comment]
- [ ] Sort positions by maturity
- [ ] Change "Normal Debt" to debt
- [ ] Add additional cards to RainbowKit top bar. One for proxy, one for FIAT balance
