### ISSUE TITLE
Refactor Forms

### ISSUE THREAD

**Issue by SolcAndMe** [fiatdao/fiat-ui-i#94]
- [x] Refactor user input variables. Retype the vars to String from BNish, rename them to be suffixed with str, rename the BN suffixed vars to have no suffix
- [ ] split up the LeverForms and BorrowForms components into separate files
- [ ] rename PositionPreview component to BorrowPreview 
- [ ] add LeverPreview component
- [ ] Refactor methods like `createLeveredPosition` into their own hook for clearer code and less unnecessary prop drilling

**Comment by 0xTARC** [comment]
task 1
https://github.com/fiatdao/fiat-ui-i/pull/103

**Comment by jFarms** [comment]
All remaining tasks are being worked on in this pr: https://github.com/fiatdao/fiat-ui-i/pull/133/files

**Comment by jFarms** [comment]
Follow up task for preview component refactor: #134
